### ISSUE TITLE
We should find a way to provide the viewer with feedback at each step

### ISSUE THREAD

**Issue by luisnaranjo733** [luisnaranjo733/info474-final#3]
Every time you step, here are the mutually exclusive possibilities that might happen

1. Nothing happens because no party left and no party could be seated
2. One or more parties leave
3. One or more parties are seated
4. One or more parties leave AND one or more parties are seated

For possibilities 2-4, these changes all happen really fast and it's hard for the viewer to understand what just happened. It would be nice if we could find a way to communicate which parties left, and which parties entered.

Ideas

1. Add a modal to the toolbar titled "what just happened". This modal would include details about what happened on the previous step, or what is going to happen on the next step
2. Automatically pop up a modal after each step that has the same information as the previous idea
3. Play with the timing of the exit and enter animations so they feel more sequential and are easier to follow (e.g. move one party at a time instead of all of them at once)

**Comment by ahnj12** [comment]
I think having the modal would be a good idea because if they don't understand what's going on, the user can get more details. It will also be really easy to show because we get all the data we need to explain what happened with the return from the seater algorithm.

Another solution to prevent the transitions from playing all at once is to disable the play button between transitions so that the transition can fully complete before they press the button again.

**Comment by luisnaranjo733** [comment]
I agree that we should add the modal that they press on demand to get more details about what just happened. Maybe we could combine idea #1 and idea #2.

I also think we should disable the step button during the transition.

**Comment by luisnaranjo733** [comment]
The analysis modal has been added. That and the transitions should be enough to satisfy the conditions of this issue
